export const GET_TRENDING_MOVIES = "GET_TRENDING_MOVIES";
export const GET_TOP_RATED_MOVIES = "GET_TOP_RATED_MOVIES";
export const GET_TRENDING_TV = "GET_TRENDING_TV";
export const GET_TOP_RATED_TV = "GET_TOP_RATED_TV";
export const GET_POPULAR_MOVIES = "GET_POPULAR_MOVIES";
export const GET_POPULAR_TV = "GET_POPULAR_TV";
export const SET_MOVIES_DETAIL = "SET_MOVIES_DETAIL";
export const SEARCH_MOVIES_LIST = "SEARCH_MOVIES_LIST";
export const SEARCH_TV_LIST = "SEARCH_TV_LIST";

export const GET_MOVIES_DETAIL = "GET_MOVIES_DETAIL";
export const GET_SIMILAR_MOVIES = "GET_SIMILAR_MOVIES";
export const GET_TV_DETAIL = "GET_TV_DETAIL";
export const GET_SIMILAR_TV = "GET_SIMILAR_TV";

export const SHOW_MODAL_SEASONS = "SHOW_MODAL_SEASONS";
export const CLOSE_MODAL_SEASONS = "CLOSE_MODAL_SEASONS";
export const SHOW_MODAL_VIDEOS = "SHOW_MODAL_VIDEOS";
export const CLOSE_MODAL_VIDEOS = "CLOSE_MODAL_VIDEOS";

export const SET_SEASONS_TV_ITEM = "SET_SEASONS_TV_ITEM";
export const GET_MOVIES_VIDEOS = "GET_MOVIES_VIDEOS";
export const GET_TV_VIDEOS = "GET_TV_VIDEOS";
export const GET_MOVIES_CREDITS = "GET_MOVIES_CREDITS";
export const GET_TV_CREDITS = "GET_TV_CREDITS";

export const ADD_REVIEWS = "ADD_REVIEWS";
