export const GET_TRENDING_MOVIES = "GET_TRENDING_MOVIES";
export const GET_TOP_RATED_MOVIES = "GET_TOP_RATED_MOVIES";
export const GET_TRENDING_TV = "GET_TRENDING_TV";
export const GET_TOP_RATED_TV = "GET_TOP_RATED_TV";
export const GET_POPULAR_MOVIES = "GET_POPULAR_MOVIES";
export const GET_POPULAR_TV = "GET_POPULAR_TV";
export const SET_MOVIES_DETAIL = "SET_MOVIES_DETAIL";
